# Generated by Django 4.1.2 on 2022-11-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_user_alter_product_confectionery'),
    ]

    operations = [
        migrations.CreateModel(
            name='confectioneryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confectionery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemss', to='store.confectionery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'unique_together': {('confectionery', 'product')},
            },
        ),
    ]
