# Generated by Django 4.1.2 on 2022-11-14 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_confectioneryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confectioneryitem',
            name='confectionery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.confectionery'),
        ),
    ]
