# Generated by Django 4.1.2 on 2022-11-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_confectioneryitem_confectionery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='confectionery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemm', to='store.confectionery'),
        ),
    ]
