# Generated by Django 4.1.2 on 2022-11-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_confectionery_featured_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='confectioneryItem',
        ),
    ]
