# Generated by Django 4.1.2 on 2022-11-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_confectioneryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='confectionery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='store.confectionery'),
        ),
    ]
